TMDT-Lab05-1212387/MVCWebAPIClient1212387/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCWebAPIClient1212387.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

TMDT-Lab05-1212387/MVCWebAPIClient1212387/Controllers/ProductController.cs
using MVCWebAPIClient1212387.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;

namespace MVCWebAPIClient1212387.Controllers
{
    public class ProductController : Controller
    {
        //
        // GET: /Product/
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult searchCategory1212387(string category)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:4083/");
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                // New code:
                HttpResponseMessage response = client.GetAsync("api/2.0/products?category=" + category).Result;
                if (response.IsSuccessStatusCode)
                {
                    var products = response.Content.ReadAsAsync<List<Product>>().Result;
                    ViewData["products"] = products;
                }
            }
            return View("getProducts");
        }
	}
}

TMDT-Lab05-1212387/MVCWebAPIClient1212387/Controllers/UsersController.cs
using MVCWebAPIClient1212387.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;

namespace MVCWebAPIClient1212387.Controllers
{
    public class UsersController : Controller
    {
        //
        // GET: /Users/
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult getAllUser1212387()
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:4083/");
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                // New code:
                HttpResponseMessage response = client.GetAsync("api/2.0/users").Result;
                if (response.IsSuccessStatusCode)
                {
                    var _users = response.Content.ReadAsAsync<List<Users>>().Result;
                    ViewData["users"] = _users;
                }
            }
            return View("getAllUser");
        }



        [HttpPost]
        public ActionResult getAllUserByUsername1212387(Users model)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:4083/");
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                // New code:
                HttpResponseMessage response = client.GetAsync("api/2.0/users/" + model.username).Result;
                if (response.IsSuccessStatusCode)
                {
                    var _users = response.Content.ReadAsAsync<Users>().Result;
                    ViewData["user"] = _users;
                }

            }
            return View("getAllUserByUsername");
        }


        [HttpPost]
        public ActionResult addUser1212387(Users model)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:4083/");
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));


                var temp = new Users() { username = model.username, password = model.password };

                // New code:
                HttpResponseMessage response = client.PostAsJsonAsync("api/2.0/users", temp).Result;
                
            }
            return RedirectToAction("getAllUser1212387");
        }


        [HttpPost]
        public ActionResult deleteUser1212387(Users model)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:4083/");
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));


                

                // New code:
                HttpResponseMessage response = client.DeleteAsync("api/2.0/users/" +model.username).Result;
            }
            return RedirectToAction("getAllUser1212387");
        }


        [HttpPost]
        public ActionResult updateUser1212387(Users model)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:4083/");
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));



                var temp = new Users() { username = model.username, password = model.confirmpassword };
                // New code:
                HttpResponseMessage response = client.PutAsJsonAsync("api/2.0/users/" + model.username, temp).Result;
            }
            return RedirectToAction("getAllUser1212387");
        }


      
    }
}

TMDT-Lab05-1212387/MVCWebAPIClient1212387/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

TMDT-Lab05-1212387/MVCWebAPIClient1212387/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TMDT-Lab05-1212387/MVCWebAPIClient1212387/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@model MVCWebAPIClient1212387.Models.Users
@using MVCWebAPIClient1212387.Models
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>getAllUser</title>
</head>
<body>
    <div>
        <a href="@Url.Action("getAllUser1212387", "Users")">
            Get All User
        </a>

        <br /><br />
        @using (Html.BeginForm("getAllUserByUsername1212387", "Users", FormMethod.Post))
        {
            <span>username: </span>
             @Html.TextBoxFor(model => model.username)
            <input type="submit" value="search">
        }

        <br /><br />
        <p>add user</p>
        @using (Html.BeginForm("addUser1212387", "Users", FormMethod.Post))
        {
            <span>username: </span>
            @Html.TextBoxFor(model => model.username)
            <br />
            <span>password: </span>
            @Html.TextBoxFor(model => model.password)
            <input type="submit" value="add">
        }

        <br /><br />
        <p>delete user</p>
        @using (Html.BeginForm("deleteUser1212387", "Users", FormMethod.Post))
        {
            <span>username: </span>
            @Html.TextBoxFor(model => model.username)
           
            <input type="submit" value="delete">
        }

        <br /><br />
        <p>update user</p>
        @using (Html.BeginForm("updateUser1212387", "Users", FormMethod.Post))
        {
            <span>username: </span>
             @Html.TextBoxFor(model => model.username)
            
           
            
            <br />
            <span>new password: </span>
            @Html.TextBoxFor(model => model.confirmpassword)
            
            <input type="submit" value="search">

        }

        <br /><br />
        <p>search category</p>
        
            <span>name category: </span>
            @{
                Product temp = new Product();
                <input type="text" value="@temp.Category" />
            }



            <button type="button" onclick="window.location.href='@Url.Action("searchCategory1212387/"+@temp.Category, "Product")'">search</button>

        


    </div>
</body>
</html>